# Generated by Django 2.1.5 on 2019-01-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('Birth_Day', models.DateField()),
            ],
        ),
    ]
