# Generated by Django 2.1.5 on 2019-01-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ex0101', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Pic', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='Ex0101/static/Ex0101/img/')),
            ],
        ),
    ]
